[tool.pdm]

[project]
name = "alien-invasion"
version = "0.1.0"
description = ""
authors = [{ name = "Donald33 Wang", email = "donald33wang@gmail.com" }]
dependencies = [
]
requires-python = ">=3.11"
license = { text = "MIT" }
